# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_number', models.IntegerField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=6)),
            ],
        ),
    ]
