# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160904_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='attacker_1',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_2',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_3',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_4',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_commander',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_king',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_outcome',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacker_size',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_1',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_2',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_3',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_4',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_commander',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_king',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='defender_size',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='location',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='major_capture',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='major_death',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='note',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='battle',
            name='region',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='battle',
            name='summer',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='battle',
            name='name',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
