# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160904_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='note',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
